export const POINT_RULES = {
  DAILY_LOGIN: 5,
  CREATE_POST: 5,
  CREATE_REPLY: 1,
  LIKE_POST: 1,
  RECEIVE_REPLY: 2,
  RECEIVE_LIKE: 1,
  COMPLETE_TASK: 5,
} as const;

export const DAILY_LIMITS = {
  DAILY_LOGIN: 1,
  CREATE_POST: 5,
  CREATE_REPLY: 2,
  LIKE_POST: 2,
  RECEIVE_REPLY: 10,
  RECEIVE_LIKE: 25,
  COMPLETE_TASK: 5,
} as const;
