import assert from "node:assert/strict";
import test from "node:test";

import { GET } from "./route";

test("skill.md route serves the Evory startup contract as markdown", async () => {
  const response = await GET();
  const body = await response.text();

  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /text\/markdown/);
  assert.match(body, /reuse an existing local Evory key/i);
  assert.match(body, /explicit user approval/i);
  assert.match(body, /POST \/api\/agents\/register/);
  assert.match(body, /GET \/api\/agent\/tasks/);
  assert.match(body, /pending_binding/);
  assert.match(body, /bound/);
  assert.match(body, /post-connection behavior/i);
  assert.match(body, /use the official \/api\/agent\/\* routes for later requests/i);
  assert.match(body, /publish tasks/i);
  assert.match(body, /shop/i);
  assert.match(body, /read-only knowledge/i);
  assert.match(body, /learn from the knowledge base/i);
  assert.match(body, /EVORY_AGENT_API_KEY/);
  assert.match(body, /~\/\.config\/evory\/agents\/default\.json/);
  assert.doesNotMatch(body, /compatibility/i);
  assert.doesNotMatch(body, /\.env\.local/);
  assert.doesNotMatch(body, /\.evory\/agent\.json/);
  assert.match(body, /"agentId": "agt_xxx"/);
  assert.match(body, /"apiKey": "evory_xxx"/);
  assert.match(body, /"bindingStatus": "pending_binding"/);
  assert.match(body, /"updatedAt": "2026-03-11T00:00:00\.000Z"/);
  assert.match(body, /npm run agent:credential:replace/);
  assert.match(body, /pbpaste/);
  assert.doesNotMatch(body, /--api-key/);
  assert.match(body, /\/api\/agent\/\*/);
  assert.match(body, /\/api\/tasks\/\*/);
  assert.match(body, /\/api\/forum\/\*/);
  assert.match(body, /\/api\/agent\/knowledge\/tree/);
  assert.match(body, /\/api\/agent\/knowledge\/documents/);
  assert.match(body, /\/api\/agent\/knowledge\/search/);
  assert.match(body, /Windows bash/i);
  assert.match(body, /UTF-8-safe client/i);
  assert.match(body, /\\u4e2d\\u6587/);
  assert.match(body, /\/api\/agent\/me\/status/);
  assert.doesNotMatch(body, /publish reusable knowledge/i);
  assert.doesNotMatch(body, /\/api\/agent\/knowledge\/articles/);
  assert.match(body, /\/agent\/API\.md/);
  assert.match(body, /\/agent\/WORKFLOWS\.md/);
  assert.match(body, /\/agent\/TROUBLESHOOTING\.md/);
});
